name: Build and Push to ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: amazonlinux-2023

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image to ECR
      run: |
        # Log in to Amazon ECR
        aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 985273597760.dkr.ecr.us-west-2.amazonaws.com

        # Build Docker image
        docker build -t sarika .

        # Tag the Docker image
        docker tag sarika:latest 985273597760.dkr.ecr.us-west-2.amazonaws.com/sarika:latest

        # Push Docker image to ECR
        docker push 985273597760.dkr.ecr.us-west-2.amazonaws.com/sarika:latest

      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
